# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArchitectureStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArchitectureStudy
  pod 'Alamofire', '~> 4.4'

  target 'ArchitectureStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArchitectureStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
